version: '1.0'

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.4
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: bind
        source: /tmp/elk/data
        target: /usr/share/elasticsearch/data
      # - type: volume
      #   source: elasticsearch
      #   target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: Iez@Nsl2_fY0PNePJL2!pOYp6%uP%hY6nu%rbtSyVF@fkOllvtq#FkNx3y!OrdEbKf9ySUHPPm!1
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - elastic

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:8.17.4
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/pipeline.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
      - "8080:8080"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elastic
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.4
    volumes:
      - ./kibana/config:/usr/share/kibana/config
    ports:
      - "5601:5601"
    networks:
      - elastic
    depends_on:
      - elasticsearch

  apm-server:
    container_name: apm-server
    image: docker.elastic.co/apm/apm-server:8.17.4
    volumes:
      - type: bind
        source: ./apm-server/apm-server.docker.yml
        target: /usr/share/apm-server/apm-server.yml
        read_only: true
    ports:
      - "8200:8200"
    environment:
      elasticsearch.hosts: "host.containers.internal:9200"
      STRICT_PERMS: false
    networks:
      - elastic
    depends_on:
      - elasticsearch
    
volumes:
  elasticsearch:

networks:
  elastic:
    :driver: bridge
